FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y ca-certificates && microdnf clean all
COPY bin/openshift-baremetal-insights-amd64 /openshift-baremetal-insights

USER 1001

ENTRYPOINT ["/openshift-baremetal-insights"]
