FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y ca-certificates && microdnf clean all
COPY bin/openshift-redfish-insights-amd64 /openshift-redfish-insights

USER 1001

ENTRYPOINT ["/openshift-redfish-insights"]
