FROM nginxinc/nginx-unprivileged:alpine

COPY dist /usr/share/nginx/html
COPY nginx-main.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

USER 0
RUN chmod -R g+rwx /var/cache/nginx /var/run /var/log/nginx /etc/nginx && \
    chown -R 1001:0 /var/cache/nginx /var/run /var/log/nginx /usr/share/nginx/html /etc/nginx
USER 1001

EXPOSE 9443

CMD ["nginx", "-g", "daemon off;"]
